### ISSUE TITLE
Request TMC Log Excel export option from the search results page

### ISSUE THREAD

**Issue by MikeSRTMC** [WSDOT/TMC-Web-Apps#10]
NWR is requesting an Excel export option on the advanced search results page, perhaps a button added at the top next to the "Printable" button.

This functionality would allow search results to be custom sorted in the Excel spreadsheet format.

![image](https://user-images.githubusercontent.com/101672074/163480551-adb33ef5-f114-4575-ac85-e7e71ca11bc7.png)

**Comment by jhudsonWA** [comment]
NW, E, OLY support this

It would be the columns shown on the normal event grid (advanced search)
