### ISSUE TITLE
Suggest change "Work Zones" in WZDB menu to "List View"

### ISSUE THREAD

**Issue by MikeSRTMC** [WSDOT/TMC-Web-Apps#13]
In the drop down menu under "Navigation", request to change "Work Zones" to "List View".

![image](https://user-images.githubusercontent.com/101672074/165355330-e2ab2f50-6d03-404a-a508-a44046d392bb.png)

**Comment by stidhat** [comment]
Or perhaps Work Zone List

**Comment by MikeSRTMC** [comment]
That could work.
