### ISSUE TITLE
Filter Permissions By Region

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/TMC-Web-Apps#17]
**Is your feature request related to a problem? Please describe.**
Currently, application permissions show everyone statewide which makes it harder to see who has permissions and to what in your area/region. 

**Describe the solution you'd like**
It would be good to add a filter for the region to filter the list down.

**Comment by jhudsonWA** [comment]
Multiple regions agree with this change. (Oly, Eastern at least)

**Comment by stidhat** [comment]
Add individuals names to permission records
