### ISSUE TITLE
Application Links Grouping

### ISSUE THREAD

**Issue by stidhat** [WSDOT/TMC-Web-Apps#2]
**Is your feature request related to a problem? Please describe.**
With so many links it can be difficult to find the required one

**Describe the solution you'd like**
Setup groups into which links can added, i.e. WSDOT, Local, Weather

**Comment by jhudsonWA** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/702446/159753076-d6333dc9-3010-471a-9271-16b7525b16d6.png">

**Comment by jhudsonWA** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/702446/159753382-7a0563bc-8137-4e90-8fed-9a46d12981ad.png">

**Comment by jhudsonWA** [comment]
ETA 3/24/2022

**Comment by MikeSRTMC** [comment]
Is this created in a region TMC log via the Administration menu?

**Comment by stidhat** [comment]
Yes, open the administration web site to edit the groups and links.
