### ISSUE TITLE
As a TMC I want to know if a SRMP is in a Work Zone so that I can call the right person.

### ISSUE THREAD

**Issue by stidhat** [WSDOT/TMC-Web-Apps#45]
When entering a TMC Log entry check for any active work zones which have been entered into the Work Zone Database.

**Comment by jhudsonWA** [comment]
@murugku Feedback: Add the contract number if it exists to the "view work zone results table". It can be empty if one does not exist.

**Comment by jhudsonWA** [comment]
Lots of support for this feature. Good to move to production when tested.

**Comment by jhudsonWA** [comment]
5 mile range / 8 hours good launch variables.
