### ISSUE TITLE
Add Mountain Pass report entry page to TMC Log application

### ISSUE THREAD

**Issue by MikeSRTMC** [WSDOT/TMC-Web-Apps#5]
Currently operators must enter mountain pass reports in a page outside the TMC Log environment.

Operators input pass information here:
http://webapps.wsdot.loc/Traffic/MountainPass/Conditions/PassEntry/

And it goes to the public page here:
https://wsdot.com/travel/real-time/mountainpasses/

Can this process be streamlined/consolidated, so that we have a specific TMC Log form page and not use another application to enter information that operators are already putting into the Log?

**Comment by jhudsonWA** [comment]
Would help with avoiding dual entry of information.

**Comment by jhudsonWA** [comment]
Any operator should be able to push these reports to Mountain Pass

**Comment by PaulTMS** [comment]
TMS DevOps has a similar request to enter pass reports in NG_TMS and have them pushed to TMC Log and the webpage.  I don't know of any particular need for the pass report data to be in TMS, so TMC Log seems like a better fit.  Also no benefit to Eastern region if it is in TMS.
