### ISSUE TITLE
WZDB gives error when "Yes" is selected for Commercial Vehicle Restrictions

### ISSUE THREAD

**Issue by MikeSRTMC** [WSDOT/TMC-Web-Apps#6]
When you select ‘yes’ on commercial vehicle restrictions, it always gives the same error ‘no commercial vehicle restrictions have been specified’.  See the attached snip ‘CVR’ below.

Screenshots

![CVR](https://user-images.githubusercontent.com/101672074/163437640-7e0181ee-1cbf-406b-91a1-fac587bebe17.PNG)

**Comment by stidhat** [comment]
Need to click the "+" button to add information about the restriction. This is then shared with the Commercial Vehicles division so they can distribute the information to CV operators.

**Comment by MikeSRTMC** [comment]
Okay, I will pass this on, ensure they can do it, and if so let you know. Thanks Tom.

**Comment by jhudsonWA** [comment]
If this solves this issue after you check with them, close it below. Thanks Mike. Good discussion!

**Comment by stidhat** [comment]
Realized what is likely happening here. I suspect they feel that saying yes will mark the entire work zone as a CV restriction and that is sufficient but the actual restriction may well be just a small portion of the zone, perhaps a single bridge which is part of a larger work zone. What needs to be entered after clicking the "+" is just the portion of roadway where the restriction exists, which may well be the entire zone but not necessarily so.

**Comment by MikeSRTMC** [comment]
Okay, I'll let them know, thanks Tom.

**Comment by MikeSRTMC** [comment]
I have not heard back from Sayuri or others in NWR about this yet.
