### ISSUE TITLE
WZDB List Page (Main Page) shows no roadway for multi-road contracts

### ISSUE THREAD

**Issue by MikeSRTMC** [WSDOT/TMC-Web-Apps#7]
NWR reports that the WZDB List Page (or Main Page) in a region shows no roadway for multi-road contracts under the columns associated with location.

This forces the viewer to click on the contract in order to see what roadways are involved. Would be better to see them at a glance on the main page list view.

Screen shot below:

![Multiple Roadways](https://user-images.githubusercontent.com/101672074/163438546-5bbf14e8-15f9-4cf4-a707-a62483828f63.PNG)
.

**Comment by stidhat** [comment]
Perhaps I need some more clarification here. If this is regarding the main list then a multi road entry has a plus sign next to the state route which will show all roads entered when clicked.

**Comment by MikeSRTMC** [comment]
Thanks Tom, I will check in with NWR on this.

**Comment by stidhat** [comment]
Could add comma delimited list of routes in SR column. Show the primary route and below that other routes in work zone.
