### ISSUE TITLE
Add status choice of "Closed" to Work Zone Database

### ISSUE THREAD

**Issue by MikeSRTMC** [WSDOT/TMC-Web-Apps#8]
When selecting the status of a Contract in WZDB, the only choices are Active, Pending and Cancelled.  

NWR requests ‘Closed’ be added to the drop down menu to better define the status (e.g. Closed and Cancelled have different meanings).

**Comment by jhudsonWA** [comment]
Verify that there is no workflow or anything that triggers when "canceled" or "closed"

Update manual to show the new status.
